services:
  muvis:
    build: &build
      context: .
      dockerfile: ci/Dockerfile
      args:
        UBUNTU_VERSION: 22.04
    image: ghcr.io/level12/copier-py-muvis


  # Run nox very close to how it will be ran in CI:
  #
  # Full tox run:
  #   ❯ docker compose run --build --rm nox
  #
  # Only the standards session:
  #   ❯ docker compose run --build --rm nox -s standards
  #
  # Only tests session and send "-k version" to pytest
  #   ❯ docker compose run --build --rm nox -s tests -- -k version
  #
  # No session limit, still send "-k version" to pytest
  #   ❯ docker compose run --build --rm nox -- -- -k version
  nox:
    extends: muvis
    build:
      # Even though we extend, use a reference so target can be specified.
      <<: *build
      target: nox
    container_name: copier-py-nox


  # Explore/troubleshoot the nox image
  # ❯ docker compose run --build --rm bash
  bash:
    extends: nox
    container_name: copier-py-bash
    entrypoint: /bin/bash
    command: ''
