[build]
dev-mode-dirs = ['.']

[metadata.hooks.requirements_txt]
files = ['requirements/base.txt']

[metadata.hooks.requirements_txt.optional-dependencies]
dev = ['requirements/dev.txt']

[version]
source = 'regex_commit'
path = 'version.py'
