[build-system]
requires = ['hatchling', 'hatch-requirements-txt']
build-backend = 'hatchling.build'

[project]
name = 'CopierPyPkg'
authors = [{name = 'Randy Syring', email = 'randy.syring@level12.io'}]
version = '0.1'
dynamic = ['dependencies', 'optional-dependencies']

[tool.hatch.build]
dev-mode-dirs = ['.']

[tool.hatch.metadata.hooks.requirements_txt]
files = ['requirements/base.txt']

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
dev = ['requirements/dev.txt']

[tool.reqs.depends]
'dev.in' = 'base.txt'
