[build-system]
requires = [
    'hatchling',
    'hatch-requirements-txt',
    'hatch-regex-commit',
]
build-backend = 'hatchling.build'


[project]
name = 'CopierPyPkg'
authors = [{name = 'Randy Syring', email = 'randy.syring@level12.io'}]
dynamic = ['version', 'dependencies', 'optional-dependencies']


[tool.reqs.depends]
'dev.in' = 'base.txt'
