version: 2
jobs:
  build:
    docker:
      - image: level12/copier-py-ci:22.04
    steps:
      - checkout

      - run:
          name: Debugging aids
          command: |
              pwd
              ls -al
              echo $PATH
              mise exec -- which python
              mise exec -- python --version

      - run:
          name: run tests
          command: |
            # The tests use `mise run demo` so the mise env needs to be
            # fully setup.
            mise exec -- python -m pip install -r requirements/ci.txt
            mise exec -- reqs sync
            mise exec -- python -m nox

      - store_test_results:
          path: ci/test-reports/

      # - run:
      #     name: push code coverage
      #     command: bash scripts/codecov-verify && bash codecov -X coveragepy -t 197f7fad-3f49-49fc-a2ec-2dbee41989f0
