version: 2.1

jobs:

  nox:

    docker:
      - image: level12/copier-py-ci:22.04

    steps:
      - checkout

      - run:
          name: run nox
          command: |
            mise run ci-nox

      - store_test_results:
          path: ci/test-reports/

workflows:
  build-all:
    jobs:
      - nox
