version: 2.1

workflows:
  build-all:
    jobs:
      - nox

jobs:

  nox:

    docker:
      - image: cimg/base:2025.02

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build it
          command: docker compose build --pull cimg
